apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-service-deployment
  namespace: go-service
spec:
  selector:
    matchLabels:
      app: go-service-app
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: go-service-app
    spec:
      containers:
      - image:  go_service-amd64:1.0
        name:  go-service-app
        resources:
          requests:
            cpu: "1000m"
          limits:
            cpu: "2000m"