apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/service-pod/
patchesStrategicMerge:
- ./kind-service-patch.yaml
images:
- name: go_service-image
  newName: go_service-amd64
  newTag: "1.0"
