apiVersion: v1
kind: Namespace
metadata:
  name:  go-service
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-service-deployment
  namespace: go-service
spec:
  selector:
    matchLabels:
      app: go-service-app
  template:
    metadata:
      labels:
        app: go-service-app
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
        - name: go-service-app
          image: go_service-image
          ports:
            - name: go-service-app
              containerPort: 3000
            - name: go-service-dbg
              containerPort: 4000
          readinessProbe:
            httpGet:
              path: /debug/readiness
              port: 4000
            initialDelaySeconds: 15

---
kind: Service
apiVersion: v1
metadata:
  name:  go-service-app-service
spec:
  selector:
    app:  go-service-app
  type: ClusterIP
  ports:
  # - name:  zipkin
  #   port: 9411
  #   targetPort: zipkin
  - name:  go-service-app
    port:  3000
    targetPort:  go-service-app
  - name: go-service-dbg
    port: 4000
    targetPort: go-service-dbg