apiVersion: v1
kind: Namespace
metadata:
  name:  go-service
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-service-deployment
  namespace: go-service
spec:
  selector:
    matchLabels:
      app: go_service
  template:
    metadata:
      labels:
        app: go_service
    spec:
      containers:
        - name: service-app
          image: service-amd64:1.0
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
---
